### ISSUE TITLE
SLAB crashes on network intensive workloads

### ISSUE THREAD

**Issue by heatd** [heatd/Onyx#89]
Using `ping -f 127.0.0.1 > /dev/null` we can find various allocator-related crashes. Note that these were all found with UBSAN and KASAN enabled.

For instance:
```
#0  halt () at arch/x86_64/debug.cpp:15
#1  0xffffffff8102dc3e in panic (msg=0xffffffff812efa3d "Assertion %s failed in %s:%u, in function %s\n") at kernel/panic.cpp:129
#2  0xffffffff8102dcab in __assert_fail (assertion=0xffffffff812f3ec7 "!list_is_empty(&cache->partial_slabs)", file=0xffffffff8130473c "kernel/mm/slab.cpp", line=596, 
    function=0xffffffff812fc7e2 "kmem_cache_alloc_refill_mag") at kernel/panic.cpp:135
#3  0xffffffff812df505 in kmem_cache_alloc_refill_mag (cache=cache@entry=0xffff80131cbdd380, pcpu=pcpu@entry=0xffff80131cbdd880, flags=flags@entry=0) at kernel/mm/slab.cpp:596
#4  0xffffffff812de7c2 in kmem_cache_alloc (cache=0xffff80131cbdd380, flags=0) at kernel/mm/slab.cpp:797
#5  0xffffffff812e0379 in kmalloc (size=176, flags=0) at kernel/mm/slab.cpp:1237
#6  0xffffffff8101b22b in operator new (size=18446744071582674336) at kernel/cppnew.cpp:17
#7  0xffffffff810a0918 in vmo_create (size=size@entry=240, priv=priv@entry=0x0 <abi::abi_data>) at kernel/mm/vm_object.cpp:39
#8  0xffffffff810e44eb in packetbuf::allocate_space (this=this@entry=0xffffd000367f9a80, length=length@entry=240) at kernel/net/packetbuf.cpp:54
#9  0xffffffff810e5449 in packetbuf_clone (original=0xffffd000367f9ee0) at kernel/net/packetbuf.cpp:195
#10 0xffffffff811025fa in loopback_send_packet (buf=0xffffffff813a6da0 <buffer_lock>, nif=0x0 <abi::abi_data>) at kernel/net/loopback.cpp:36
#11 0xffffffff810ce114 in ip::v4::send_packet (flow=..., buf=buf@entry=0xffffd000367f9ee0, options=...) at kernel/net/ipv4/ipv4.cpp:347
#12 0xffffffff810c6a1c in icmp::icmp_socket::sendmsg (this=<optimized out>, msg=<optimized out>, flags=<optimized out>) at kernel/net/ipv4/icmp.cpp:310
#13 0xffffffff81128f41 in socket_sendmsg (sock=0xffff80131e783900, umsg=0x556f5b691c20, flags=0) at kernel/net/socket.cpp:1322
#14 sys_sendmsg (sockfd=<optimized out>, msg=0x556f5b691c20, flags=0) at kernel/net/socket.cpp:1374
#15 0xffffffff811cde12 in do_syscall64 (frame=<optimized out>) at arch/x86_64/syscall.cpp:44
#16 0xffffffff811b9b0f in syscall_ENTRY64 () at arch/x86_64/entry.S:130
#17 0x0000000000000033 in abi::abi_data ()
```

and

Page fault inside list_remove (with 0xDEB5 aka LIST_REMOVE_POISON)

```
0xffff804d72890ca0:     0xffff804d72890cd0      0xffffffff812df9a6 <_ZL17kmem_free_to_slabP10slab_cacheP4slabPv+166>
0xffff804d72890cd0:     0xffff804d72890cf0      0xffffffff812dd898 <_ZN10quarantine3popEv+40>
0xffff804d72890cf0:     0xffff804d72890d30      0xffffffff812ddb98 <_ZN10quarantine5flushEv+120>
0xffff804d72890d30:     0xffff804d72890e50      0xffffffff810b2bb1 <_Z15page_do_reclaimP12reclaim_data+257>
0xffff804d72890e50:     0xffff804d72890fd8      0xffffffff8109fd60 <_ZL10pagedaemonPv+1168>
0xffff804d72890fd8:     0xffff804d72890ff8      0xffffffff811cec26 <_ZN3x868internal19kernel_thread_startEPv+70>
```

Are these triggered *because* of memory pressure + the KASAN quarantine? I can't tell.

**Comment by heatd** [comment]
Fixed by 2b8f658
